routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();
//home
//Route::group(
//    ['middleware'=>'auth']

Route::get("/logout", "Auth\LoginController@logout")->name("get-logout");
Route::middleware('auth')->group(function () {

    Route::group([
        'prefix' => 'customer'
    ], function () {
        Route::get("/orders/{id}", "Customer\OrderController@show")->name("customer.show");
        Route::get("/orders", "Customer\OrderController@index")->name("customer.index");
    });

    Route::group([
        'middleware' => 'is_admin',
        'prefix' => 'admin'], function () {
        Route::get("/orders/{id}", "Admin\OrdersController@show")->name("order.show");
        Route::get("/orders", "Admin\OrdersController@index")->name("home");
        Route::resource("/categories", "Admin\CategoryController");
        Route::resource('/products', 'Admin\ProductController');
    });


});

//open
Route::post('/test', 'BasketController@test')->name('test');
Route::get("/", "TestController@index")->name("index");
Route::get("/category/{category}", 'TestController@category')->name('categories');
Route::get("/categories", 'TestController@categories_all')->name('categories_all');;
Route::get('/card/{category}/{product?}', 'TestController@products_card')->name('product_card');

//basket routes
Route::get('/order', 'BasketController@order')->name('order')->middleware('basket_not_empty')->middleware('auth');
Route::post('/order/confirm', 'BasketController@orderConfirm')->name('order-confirm');
Route::get('basket/add/{id?}', 'BasketController@addInBasket')->name('add_get_basket');
Route::group([
    'middleware' => 'basket_not_empty',
    'prefix' => 'basket'
], function () {
    Route::get('/', 'BasketController@basket')->name('basket');
//add-remove product in basket
    Route::post('/add/{id?}', 'BasketController@addInBasket')->name('add_in_basket');
    Route::post('/remove/{id?}', 'BasketController@removeFromBasket')->name('rem_from_basket');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['id', 'name', 'categotry_id', 'slug', 'price', 'description', 'image', 'hit', 'new'];
//   public function getCategory(){
//       $collection= Category::find($this->categotry_id);
//      //       $collection=Category::where('id', $this->categotry_id)->first();//variant 2
//      // якщо умова(типу where) з лівої сторони то це кусок запроса, якщо правої сторони -це робота з колекцією
//
//      //       $collection=Category::where('id', $this->categotry_id)->get(); return query
//      //       $collection=Category::where('id', $this->categotry_id);//query build
//
//      return $collection;
//   }

// public function category(){
//     return $this->belongsTo(Product::class, );
// }
    public function category()
    {
//     return $this->belongsTo('App\Category', "categotry_id", 'id' );
        return $this->belongsTo(Category::class, "categotry_id", 'id');
    }

    public function getSummProduct()
    {
        return $this->price * $this->pivot->count;

    }
    public function setNewAttribute($value)
    {
        $this->attributes['new'] = $value === 'on' ? 1 : 0;
    }
    public function setHitAttribute($value)
    {
        $this->attributes['hit'] = $value === 'on' ? 1 : 0;
    }
    public function isNew()
    {
        return $this->new===1;
    }

    public function isHit()
    {
        return $this->hit===1;
    }

}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::paginate(10);
        return view('admin.products.admin_products', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
//        dd($categories);
        return view('admin.products.form_products', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
//        dd($request->all());
        if ($request->has('image')) {
            $patch = $request->file('image')->store('products', 'public');
        } else {
            $patch = null;
        }

        $params = $request->all();
        $params['image'] = $patch;

//        Product::create($req);
        Product::create($params);
        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('admin.products.show_products', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::all();
        return view('admin.products.form_products', compact('categories', 'product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Product $product)
    {
//        dd($request->all());
        if ($request->has('image')) {
            Storage::disk('public')->delete($product->image);
            $patch = $request->file('image')->store('products', 'public');
        } else {
            $patch = $product->image;
        }
//        dd($product->image);
//        dd(Storage::delete($product->image));
        $req = $request->all();
        $req['image'] = $patch;
        foreach (['new', 'hit'] as $fieldName) {
            if (!isset($req[$fieldName])) {
                $req[$fieldName] = 0;
            }
        }
//        dd($req);
        $product->update($req);
        return redirect()->route("products.index");
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('products.index');
    }
}

resources/views/admin/products/admin_products.blade.php
@extends('admin.home.home_layout')
@section('title', 'Товари')
@section('content')
    <div class="container" style="margin-top: 70px;">

            <table class="table table-hover">

                <thead>
                <tr>
                    <th>#</th>
                    <th style="max-width: 286px;">Назва</th>
                    <th >prefix</th>
                    <th >Категорія</th>
                    <th >Картинка</th>
                    <th >Ціна</th>
                    <th >Дії</th>
                </tr>
                </thead>
                <tbody>
                @foreach($products as $product)
                <tr>

                    <td>{{$product->id}}</td>
                    <td style="max-width: 286px;">{{$product->name}}</td>
                    <td>{{$product->slug}}</td>
                    <td>{{$product->category->name}}</td>
                    <td><img style="max-height: 28px" src="{{\Illuminate\Support\Facades\Storage::url($product->image)}}" alt="image"></td>
                    <td>{{number_format($product->price, 2, '.', ' ')}} грн.</td>
                    <td>
                        <form action="{{route('products.destroy', $product->id)}}" method="POST" id="main_input_box">
                            @method('DELETE')
                            @csrf
                        <a href="{{route('products.show',$product->id)}}" class="btn btn-primary"> show</a>
                        <a href="{{route('products.edit', $product->id)}}" class="btn btn-warning"> edit</a>
                        <button  class="btn btn-danger"> remove</button>

                           </form>
                        </td>
                </tr>
                @endforeach

                </tbody>

            </table>
        <ul class="pagination justify-content-center" style="margin:20px 0">
            <li class="page-item">{{$products->links()}}</li>
        </ul>
            <a href="{{route('products.create')}}" class="btn btn-success"> Додати товар</a>

    </div>
@endsection

resources/views/admin/products/form_products.blade.php
@extends('admin.home.home_layout')
@isset($product)
    @section('title', 'Редагувати продукт')
@else
    @section('title', 'Створити продукт')
@endisset
@section('content')
    {{--    {{dd($categories)}}--}}
    <div class="container" style="margin-top: 70px;">
        <form enctype="multipart/form-data" method="POST" id="main_input_box"
              @isset($product)
              action="{{route('products.update',$product)}}">
            @method('PUT')
            @else

                action="{{route('products.store')}}">
            @endisset
            @csrf


            <div class="form-group edit-form">
                <label for="categotry_id" class="control-label col-lg-offset-2 col-lg-2"> Select category</label>
                <div class="row">
                    <div class="col-lg-6">

                        <select name="categotry_id" class="custom-select " id="inlineFormCustomSelectPref">

                            @foreach($categories as $category)
                                {{--                                <option value="{{old('categotry_id', isset($category->id) ? $category->name :null)}}">{{$category->name}} </option>--}}
                                <option value="{{$category->id}}">{{$category->name}} </option>
                            @endforeach
                        </select>
                    </div>
                </div>

            </div>

            <div class="form-group edit-form">
                <label for="prefix" class="control-label col-lg-offset-2 col-lg-2">Код(slug): </label>
                <div class="row">
                    <div class="col-lg-6">
                        <input type="text" name="slug" id="prefix"
                               value="{{old('slug', isset($product->slug) ? $product->slug:null )}}"
                               class="form-control">
                    </div>
                 @include('admin.errors', ['fieldName'=>'slug'])
                </div>
            </div>


            <div class="form-group edit-form">
                <label for="name" class="control-label col-lg-offset-2 col-lg-2">Назва: </label>
                <div class="row">
                    <div class="col-lg-6">
                        <input type="text" name="name" id="name"
                               value="{{old('name',isset($product->name)? $product->name : null )}}"
                               class="form-control">
                    </div>
                    @include('admin.errors', ['fieldName'=>'name'])
                </div>

                <div class="form-group edit-form">
                    <label for="price" class="control-label col-lg-offset-2 col-lg-2">Price: </label>
                    <div class="row">
                        <div class="col-lg-6">
                            <input type="price" name="price" id="price"
                                   value="{{old('price', isset ($product) ? $product->price : null)}}"
                                   class="form-control">
                        </div>
                        @include('admin.errors', ['fieldName'=>'price'])
                    </div>
                </div>
                <div class="form-group edit-form">
                    <label class="control-label col-lg-offset-2 col-lg-2" for="description">Короткий опис:</label>
                    <div class="row">
                        <div class="col-lg-6">
                            <textarea name="description" class="form-control" id="description"
                                      rows="3">{{old('description')}}@isset($product->description){{$product->description}}@endisset</textarea>
                        </div>
                        @include('admin.errors', ['fieldName'=>'description'])
                    </div>
                </div>
                <div class="form-group edit-form">
                    <label class="control-label col-lg-offset-2 col-lg-2" for="image">Select image for
                        product</label>
                    <div class="edit-form col-lg-6">
                        <input type="file" name="image" class="form-control-file">
                    </div>
                </div>
                <div class="filters row">

                        @foreach(['hit'=>'Хіт',
                        'new'=>'Новинка'
                         ] as $field=>$title)
                        <div class="col-sm-2 col-md-2">
                        <label for="{{$field}}">
                                <input type="checkbox" name="{{$field}}" id="" @if(isset($product)&&$product->$field===1) checked="checked" @endif> {{$title}}
                            </label>
                    </div>
                    @endforeach




                </div>

                <div class="edit-form">
                    <div class="col-lg-5"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success"> Зберегти</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/products/show_products.blade.php
@extends('admin.home.home_layout')
@section('title', 'redact')
@section('content')
    <div class="container" style="margin-top: 70px;">
        <div class="col-lg-9" role ="form" id="main_input_box">
            <table class=" table table-hover">
                <thead>
                <tr>

                    <th>#</th>
                    <th>parametr</th>

                </tr>
                </thead>
                <tbody>
                <tr>
                    <div class="col-lg-3 text-center" id="img-div">
                        @if($product->isNew())
                            <span class="badge badge-warning">Новинка</span>
                        @endif
                        @if($product->isHit())
                            <span class="badge badge-success">Хіт продаж</span>
                        @endif
                        <img style="height: 256px" src="{{\Illuminate\Support\Facades\Storage::url($product->image)}}" alt="image">

                    </div>
                    <td>ID</td>
                    <td>{{$product->id}}</td>

                </tr>
                <tr>

                    <td>Категорія</td>
                    <td>{{$product->category->name}}</td>

                </tr>
                <tr>

                    <td>Найменування</td>
                    <td>{{$product->name}}</td>

                </tr>

                <tr>

                    <td>Опис</td>
                    <td>{!!nl2br($product->description)!!}</td>


                </tr>
                <tr>

                    <td>Ціна</td>
                    <td>{{number_format($product->price, 2,'.',' ')}} грн.</td>


                </tr>
                </tbody>
            </table>
        </div>


        <div class="col-lg-12">
        <a href="{{route('products.index')}}" class="btn btn-success"> В список products</a>
        </div>
        </div>


@endsection