routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();
//home
//Route::group(
//    ['middleware'=>'auth']

Route::get("/logout", "Auth\LoginController@logout")->name("get-logout");
Route::middleware('auth')->group(function () {

    Route::group([
        'prefix' => 'customer'
    ], function () {
        Route::get("/orders/{id}", "Customer\OrderController@show")->name("customer.show");
        Route::get("/orders", "Customer\OrderController@index")->name("customer.index");
    });

    Route::group([
        'middleware' => 'is_admin',
        'prefix' => 'admin'], function () {
        Route::get("/orders/{id}", "Admin\OrdersController@show")->name("order.show");
        Route::get("/orders", "Admin\OrdersController@index")->name("home");
        Route::resource("/categories", "Admin\CategoryController");
        Route::resource('/products', 'Admin\ProductController');
    });


});

//open
Route::post('/test', 'BasketController@test')->name('test');
Route::get("/", "TestController@index")->name("index");
Route::get("/category/{category}", 'TestController@category')->name('categories');
Route::get("/categories", 'TestController@categories_all')->name('categories_all');;
Route::get('/card/{category}/{product?}', 'TestController@products_card')->name('product_card');

//basket routes
Route::get('/order', 'BasketController@order')->name('order')->middleware('basket_not_empty')->middleware('auth');
Route::post('/order/confirm', 'BasketController@orderConfirm')->name('order-confirm');
Route::get('basket/add/{id?}', 'BasketController@addInBasket')->name('add_get_basket');
Route::group([
    'middleware' => 'basket_not_empty',
    'prefix' => 'basket'
], function () {
    Route::get('/', 'BasketController@basket')->name('basket');
//add-remove product in basket
    Route::post('/add/{id?}', 'BasketController@addInBasket')->name('add_in_basket');
    Route::post('/remove/{id?}', 'BasketController@removeFromBasket')->name('rem_from_basket');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable=['id','name','slug', 'image', 'description'];
    //
    public function  product(){
        return $this->hasOne(Category::class);
    }
    public function products(){
//        return $this->hasMany('App\Product', "categotry_id", 'id' );
        return $this->hasMany(Product::class, "categotry_id", 'id' );
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        $categories = Category::get();
        $categories = Category::paginate(10);
//        dd($categories);
        return view('admin.categories.admin_categories', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $categories = Category::get();
//        dd($categories);
        return view('admin.categories.form_categories');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
//                dd($request->all());
        if ($request->has('image')) {
            $puth = $request->file('image')->store('categories', 'public');
        } else {
            $puth = null;
        }
        $req = $request->all();
        $req['image'] = $puth;
        $stored = Category::create($req);
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Category $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('admin.categories.show_edit_category', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Category $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.form_categories', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Category $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $req = $request->all();
        if ($request->has('image')) {
            Storage::disk('public')->delete($category->image);
            $puth = $request->file('image')->store('categories', 'public');
        } else {
            $puth = ($category->image);
        }


        $req['image'] = $puth;
        $category->update($req);
        return redirect()->route('categories.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Category $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('categories.index');
    }
}

resources/views/admin/categories/admin_categories.blade.php
@extends('admin.home.home_layout')
@section('title', 'Категорії')
@section('content')
    <div class="container" style="margin-top: 70px;">

            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Ім'я</th>
                    <th>prefix</th>
                    <th>Іконка</th>
                    <th>Дії</th>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $category)
                <tr>

                    <td>{{$category->id}}</td>
                    <td>{{$category->name}}</td>
                    <td>{{$category->slug}}</td>
                    <td><img style="max-height: 28px" src="{{\Illuminate\Support\Facades\Storage::url($category->image)}}" alt="image"></td>
                    <td>
                        <form action="{{route('categories.destroy',$category->id)}}" method="POST" id="main_input_box">
                        <a href="{{route('categories.show',$category->id)}}" class="btn btn-primary"> show</a>
                        <a href="{{route('categories.edit', $category->id)}}" class="btn btn-warning"> edit</a>
                            @csrf
                            @method('DELETE')
                        <button  class="btn btn-danger"> remove</button>
{{--                            <input type="submit" value="ok">--}}

                        </form>
                    </td>
                </tr>
                @endforeach
                </tbody>
            </table>
        <ul class="pagination justify-content-center" style="margin:20px 0">
            <li class="page-item">{{$categories->links()}}</li>
        </ul>
            <a href="{{route('categories.create')}}" class="btn btn-success"> Додати категорію</a>

    </div>
@endsection

resources/views/admin/categories/form_categories.blade.php
@extends('admin.home.home_layout')
@isset($category)
    @section('title', 'Редагувати категорію')
    @else
@section('title', 'Створити категорію')
        @endisset

@section('content')
    <div class="container" style="margin-top: 70px;">
        <form method="POST"  enctype="multipart/form-data"  id="main_input_box"
              @isset($category)
              action="{{route('categories.update', $category)}}">
            @else
                action="{{route('categories.store')}}" >
            @endisset
                @isset($category)
                    @method('PUT')
                @endisset
            @csrf
            <div class="form-group edit-form">

                <label for="prefix" class="control-label col-lg-offset-2 col-lg-2">Код(slug): </label>
                <div class="row">
                    <div class="col-lg-6 col-md-12">
                        <input type="text" name="slug" id="prefix" value="{{old('slug', isset($category) ? $category->slug : null)}}" class="form-control">
                    </div>

               @error('slug')
                <div class="alert alert-danger col-lg-6 col-md-12">
                    {{$message}}
                </div>
                @enderror
                </div>
            </div>

            <div class="form-group edit-form">
                <label for="name" class="control-label col-lg-offset-2 col-lg-2">Назва: </label>
                <div class="row">
                <div class="col-lg-6 col-md-12">
                    <input type="text" name="name" id="name" value="{{old("name", isset($category) ? $category->name: null)}}" class="form-control">
                </div>
                    @error('name')
                    <div class="col-lg-6 col-md-12  alert alert-danger">
                        {{$message}}
                    </div>
                    @enderror
                </div>
            </div>


            <div class="form-group edit-form">
                <label class="control-label col-lg-offset-2 col-lg-2" for="description">Короткий опис:</label>
            <div class="row">
                <div class="col-lg-6 col-md-12">
                <textarea name="description"  class="form-control" id="description" rows="3">{{old('description', isset($category) ? $category->description : null)}}</textarea>
            </div>
                @error('description')
                <div class="col-lg-6 col-md-12  alert alert-danger">
                    {{$message}}
                </div>
                @enderror
            </div>
            </div>

                <div class="form-group edit-form">
                    <label class="control-label col-lg-offset-2 col-lg-2">Select image for category</label>
                    <div class="edit-form col-lg-6">
                        <input  type="file" name="image" class="form-control-file">
                    </div>
                </div>
            <br><br>

            <div class="edit-form">
                <div class="col-lg-5"></div>
                <div class="col-lg-6">
                    <button  type="submit" class="btn btn-success"> Зберегти</button>
{{--                    <input  type="submit"  value=" Зберегти" class="btn btn-success">--}}
                </div>
            </div>
    </form>
    </div>
@endsection

resources/views/admin/categories/show_edit_category.blade.php
@extends('admin.home.home_layout')
@section('title', 'redact')
@section('content')
    <div class="container" style="margin-top: 70px;">
        <div class="col-lg-9" role ="form" id="main_input_box">
            <table class=" table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>parametr</th>

                </tr>
                </thead>
                <tbody>
                <tr>

                    <td>ID</td>
                    <td>{{$category->id}}</td>

                </tr>
                <tr>

                    <td>name</td>
                    <td>{{$category->name}}</td>

                </tr>

                <tr>

                    <td>Опис</td>
                    <td>{!!$category->description!!}</td>


                </tr>
                <tr>

                    <td>Одиниць товару в категорії</td>
                    <td>{{$category->products->count()}}</td>


                </tr>
                </tbody>
            </table>
        </div>

                    <div class="col-lg-3" id="img-div">
                        <img style="height: 128px" src="{{Storage::url($category->image)}}" alt="image">
{{--                        <img style="height: 128px" src="{{$category->image}}" alt="image">--}}

                    </div>
        <div class="col-lg-12">
        <a href="{{route('categories.index')}}" class="btn btn-default"> В список категорій</a>
        </div>
        </div>


@endsection